### ISSUE TITLE
Build for updated to 0.9.8, with up-to-date Freedesktop runtimes

### ISSUE THREAD

**Issue by neufeind** [flathub/vn.hoabinh.quan.CoBang#2]
Hi. Could you please consider a build of 0.9.8 (currently flathub only has 0.9.7) and in that step also move to newer Freedesktop-runtimes?

runtime org.freedesktop.Platform.VAAPI.Intel branch 20.08 is end-of-life
runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life
=> org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

**Comment by neufeind** [comment]
Also see #1

**Comment by hongquan** [comment]
Thanks for reminding. I will do it today.

**Comment by hongquan** [comment]
Version 0.9.9 is to be released, with updated runtime: https://github.com/flathub/vn.hoabinh.quan.CoBang/pull/3
