### ISSUE TITLE
GNOME 44 runtime available

### ISSUE THREAD

**Issue by JamiKettunen** [flathub/vn.hoabinh.quan.CoBang#7]
Just saw this app on my shrinking `flatpak list --app-runtime=org.gnome.Platform//43` output, nothing too urgent though :)

**Comment by hongquan** [comment]
Thanks.

The v0.10.2 fixes this and is waiting for FlatHub to publish: https://github.com/flathub/vn.hoabinh.quan.CoBang/pull/8

**Comment by JamiKettunen** [comment]
Since the creation of this issue there was GNOME 45 release and with it the GNOME 45 runtime for flatpak, but oh well this is better for now than an EoL runtime which 43 has become since then :)

**Comment by hongquan** [comment]
Thanks. I didn't know that GNOME has released v45. I will update CoBang, too.
